services:
  archipelago-bot:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    build: .
    container_name: archipelago-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    network_mode: host