services:
  archipelago-bot:
    image: ghcr.io/mikamk4/archipelago-bot:latest
    container_name: archipelago-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    network_mode: host