name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.repo_vars.outputs.image_name }}
      image_tag: ${{ steps.repo_vars.outputs.image_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set image name and tag to lowercase
        id: repo_vars
        run: |
          # Transform repository name to lowercase for Docker compatibility
          IMAGE_NAME="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          # Get the short git commit SHA as the unique tag
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.repo_vars.outputs.image_name }}:latest
            ${{ steps.repo_vars.outputs.image_name }}:${{ steps.repo_vars.outputs.image_tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/archipelago-bot

            export IMAGE_NAME=${{ needs.build-and-push.outputs.image_name }}
            export IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            
            git pull

            docker pull $IMAGE_NAME:$IMAGE_TAG

            docker compose up -d --remove-orphans