name: CI/CD Pipeline

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
          image_name: ${{ steps.repo_vars.outputs.image_name }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set image name to lowercase
              id: repo_vars
              run: echo "image_name=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ghcr.io/${{ steps.repo_vars.outputs.image_name }}:latest

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                script: |
                    cd /app/archipelago-bot

                    echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
                    echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env
                    echo "SERVER_PUBLIC_IP=${{ secrets.SERVER_HOST }}" >> .env

                    docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
                    docker pull ghcr.io/${{ github.repository }}:latest
                    docker-compose down
                    docker-compose up -d

                    docker image prune -f